package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"doctor-booking-system/internal/db/models"
	"doctor-booking-system/internal/utils"
	"fmt"
)

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	user, ok := utils.GetUserFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return &models.User{
		ID:        fmt.Sprintf("%d", user.ID),
		Name:      user.Name,
		Email:     user.Email,
		Role:      models.UserRole(user.Role),
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
	}, nil
}

func (r *queryResolver) Doctors(ctx context.Context) ([]*models.Doctor, error) {
	var doctors []models.Doctor
	if err := r.DB.Gorm.Find(&doctors).Error; err != nil {
		return nil, err
	}

	var result []*models.Doctor
	for _, d := range doctors {
		result = append(result, &models.Doctor{
			ID:        fmt.Sprintf("%d", d.ID),
			Name:      d.Name,
			Specialty: d.Specialty,
			Bio:       d.Bio,
			CreatedAt: d.CreatedAt,
			UpdatedAt: d.UpdatedAt,
		})
	}

	return result, nil
}
